"""
validate.py
Nexus Consulting Group — Migration Validation

Queries the migrated monday.com boards and compares them against the source CSV.
Produces a formatted console report and writes validation_report.json.

Key feature: status normalization checks display the original raw CSV value
alongside the expected normalized value, confirming the transformation happened
correctly (not just that the end state is valid).

Requires board_config.json (generated by migration.py).
Usage: python validate.py
"""

import csv
import json
import os
import sys
import time
from datetime import datetime

import requests
from dotenv import load_dotenv

load_dotenv()

# ── Configuration ─────────────────────────────────────────────────────────────
API_TOKEN   = os.getenv("MONDAY_API_TOKEN")
API_URL     = "https://api.monday.com/v2"
HEADERS     = {
    "Authorization": API_TOKEN,
    "Content-Type":  "application/json",
    "API-Version":   "2024-01",
}
CSV_PATH    = "nexus_smartsheet_export.csv"
CONFIG_PATH = "board_config.json"
REPORT_PATH = "validation_report.json"

# ── API helpers ───────────────────────────────────────────────────────────────

def run_query(query: str, variables: dict = None, retries: int = 3) -> dict:
    payload = {"query": query}
    if variables:
        payload["variables"] = variables
    for attempt in range(1, retries + 2):
        resp = requests.post(API_URL, json=payload, headers=HEADERS)
        if resp.status_code == 429 and attempt <= retries:
            wait = 10 * (2 ** (attempt - 1))
            print(f"  Rate limited — waiting {wait}s before retry {attempt}/{retries}...")
            time.sleep(wait)
            continue
        resp.raise_for_status()
        data = resp.json()
        if "errors" in data:
            raise Exception(f"GraphQL error: {data['errors']}")
        return data["data"]


def fetch_board_items(board_id: str) -> list[dict]:
    """Retrieves all items from a board including all column values."""
    query = """
    query GetItems($boardId: ID!) {
        boards(ids: [$boardId]) {
            items_page(limit: 500) {
                items {
                    id
                    name
                    column_values {
                        id
                        text
                        value
                        ... on BoardRelationValue {
                            linked_items { id }
                        }
                    }
                }
            }
        }
    }
    """
    data = run_query(query, {"boardId": board_id})
    return data["boards"][0]["items_page"]["items"]


# ── Column value helpers ──────────────────────────────────────────────────────

def col_text(item: dict, col_id: str) -> str:
    for cv in item["column_values"]:
        if cv["id"] == col_id:
            return (cv.get("text") or "").strip()
    return ""


def col_has_value(item: dict, col_id: str) -> bool:
    for cv in item["column_values"]:
        if cv["id"] == col_id:
            text  = (cv.get("text")  or "").strip()
            value = (cv.get("value") or "").strip()
            # board_relation columns expose linked items via linked_items, not text/value
            linked = cv.get("linked_items") or []
            return bool(text) or bool(linked) or (bool(value) and value not in ("null", '""', "{}", "[]"))
    return False


# ── Validation checks ─────────────────────────────────────────────────────────

def check_record_counts(source_rows, source_eng_ids, monday_engs, monday_dels):
    """Verifies total record counts match the source."""
    checks = []
    for label, expected, actual in [
        ("Engagement count", len(source_eng_ids), len(monday_engs)),
        ("Deliverable count", len(source_rows),   len(monday_dels)),
    ]:
        checks.append({
            "check":    label,
            "expected": expected,
            "actual":   actual,
            "pass":     expected == actual,
            "detail":   None if expected == actual else f"Delta: {actual - expected:+d}",
        })
    return checks


def check_engagement_ids(source_rows, monday_engs, eng_cols):
    """Verifies every source engagement_id is present in monday."""
    source_ids = set(r["engagement_id"] for r in source_rows)
    monday_ids = set(col_text(item, eng_cols["engagement_id"]) for item in monday_engs)
    missing    = sorted(source_ids - monday_ids)
    return {
        "check":   "All engagement IDs present",
        "pass":    len(missing) == 0,
        "detail":  f"Missing: {missing}" if missing else None,
        "missing": missing,
    }


def check_deliverable_ids(source_rows, monday_dels, del_cols):
    """Verifies every source deliverable_id is present in monday."""
    source_ids = set(r["deliverable_id"] for r in source_rows)
    monday_ids = set(col_text(item, del_cols["deliverable_id"]) for item in monday_dels)
    missing    = sorted(source_ids - monday_ids)
    return {
        "check":   "All deliverable IDs present",
        "pass":    len(missing) == 0,
        "detail":  f"Missing: {missing}" if missing else None,
        "missing": missing,
    }


def check_orphaned_deliverables(monday_dels, del_cols):
    """Flags deliverables with no linked engagement (broken FK relationship)."""
    orphans = [
        {"id": item["id"], "name": item["name"]}
        for item in monday_dels
        if not col_has_value(item, del_cols["engagement"])
    ]
    return {
        "check":   "No orphaned deliverables (all linked to an engagement)",
        "pass":    len(orphans) == 0,
        "detail":  f"{len(orphans)} orphan(s) found" if orphans else None,
        "orphans": orphans,
    }


def check_required_fields(monday_dels, del_cols):
    """
    Flags deliverables missing fields Derek specifically called out:
    assignee, due date, and hours estimated.
    """
    issues = []
    required = {
        "assignee": del_cols["assignee"],
        "due_date": del_cols["due_date"],
        "hours":    del_cols["hours"],
    }
    for item in monday_dels:
        for field_name, col_id in required.items():
            if not col_has_value(item, col_id):
                issues.append({"item": item["name"], "missing_field": field_name})
    return {
        "check":  "Required deliverable fields populated (assignee, due date, hours)",
        "pass":   len(issues) == 0,
        "detail": f"{len(issues)} issue(s)" if issues else None,
        "issues": issues,
    }


def check_engagement_status_normalization(source_rows, monday_engs, eng_cols, status_map):
    """
    For each engagement, compares the raw CSV status value against what
    we expect after normalization, then confirms what's actually in monday.

    This proves the transformation happened correctly, not just that the
    end state is valid.

    Report format per item:
      ✓  'In Progress' → 'Active'     (monday: 'Active')
      ✗  'Active'      → 'Active'     (monday: 'In Progress'  ← unexpected)
    """
    # Build a lookup: engagement name → raw CSV status
    raw_by_name = {}
    for row in source_rows:
        name = row["engagement_name"].strip()
        if name not in raw_by_name:
            raw_by_name[name] = row["engagement_status"].strip()

    results = []
    for item in monday_engs:
        raw_status      = raw_by_name.get(item["name"], "")
        expected_norm   = status_map.get(raw_status.lower(), "Not Started")
        actual_in_monday = col_text(item, eng_cols["status"])
        match            = actual_in_monday == expected_norm

        results.append({
            "engagement":      item["name"],
            "raw_csv_value":   raw_status,
            "expected":        expected_norm,
            "actual_in_monday": actual_in_monday,
            "pass":            match,
        })

    failures = [r for r in results if not r["pass"]]
    return {
        "check":      "Engagement status normalization (raw CSV → monday value)",
        "pass":       len(failures) == 0,
        "detail":     f"{len(failures)} mismatch(es)" if failures else None,
        "results":    results,
        "failures":   failures,
    }


def check_deliverable_status_normalization(source_rows, monday_dels, del_cols, status_map):
    """
    For each deliverable, shows: raw CSV value → expected normalized → actual in monday.
    Confirms 'Working on it', 'Not Started' etc. were correctly transformed.
    """
    raw_by_id = {row["deliverable_id"]: row["deliverable_status"].strip() for row in source_rows}

    # Build a lookup monday deliverable_id col → item
    results = []
    for item in monday_dels:
        del_id          = col_text(item, del_cols["deliverable_id"])
        raw_status      = raw_by_id.get(del_id, "")
        expected_norm   = status_map.get(raw_status.lower(), "To Do")
        actual_in_monday = col_text(item, del_cols["status"])
        match            = actual_in_monday == expected_norm

        results.append({
            "deliverable":     item["name"],
            "deliverable_id":  del_id,
            "raw_csv_value":   raw_status,
            "expected":        expected_norm,
            "actual_in_monday": actual_in_monday,
            "pass":            match,
        })

    failures = [r for r in results if not r["pass"]]
    return {
        "check":    "Deliverable status normalization (raw CSV → monday value)",
        "pass":     len(failures) == 0,
        "detail":   f"{len(failures)} mismatch(es)" if failures else None,
        "results":  results,
        "failures": failures,
    }


# ── Report rendering ──────────────────────────────────────────────────────────

def print_section(title: str):
    print(f"\n  {'─' * 54}")
    print(f"  {title}")
    print(f"  {'─' * 54}")


def render_status_normalization_check(check: dict, label_width: int = 28):
    """
    Renders status normalization results showing every transformation,
    not just failures — so the demo audience can see the full audit trail.
    """
    icon   = "✓" if check["pass"] else "✗"
    status = "PASS" if check["pass"] else "FAIL"
    print(f"  [{status}] {icon} {check['check']}")
    if check.get("detail"):
        print(f"          → {check['detail']}")
    print()

    # Show all transformations — highlight failures
    for r in check.get("results", []):
        raw      = r["raw_csv_value"]
        expected = r["expected"]
        actual   = r["actual_in_monday"]
        changed  = raw != expected   # was a transformation needed?
        matched  = r["pass"]

        row_icon = "✓" if matched else "✗"
        arrow    = f"'{raw}' → '{expected}'" if changed else f"'{raw}' (no change)"
        monday_note = f"  (monday: '{actual}')" if not matched else ""
        name     = r.get("deliverable", r.get("engagement", ""))

        print(f"    {row_icon}  {name[:label_width]:<{label_width}}  {arrow}{monday_note}")


def render_check(check: dict):
    icon   = "✓" if check["pass"] else "✗"
    status = "PASS" if check["pass"] else "FAIL"
    print(f"  [{status}] {icon} {check['check']}")
    if not check["pass"] and check.get("detail"):
        print(f"          → {check['detail']}")
    for orphan in check.get("orphans", []):
        print(f"            Orphan: {orphan['name']} (item id: {orphan['id']})")
    for issue in check.get("issues", []):
        print(f"            {issue['item']}: missing '{issue['missing_field']}'")
    for mid in check.get("missing", []):
        print(f"            Missing ID: {mid}")


def render_report(count_checks, id_checks, field_checks, eng_status_check, del_status_check):
    all_checks = count_checks + id_checks + field_checks + [eng_status_check, del_status_check]
    passed = sum(1 for c in all_checks if c.get("pass"))
    total  = len(all_checks)
    failed = total - passed

    print("\n" + "=" * 60)
    print("  MIGRATION VALIDATION REPORT")
    print("  Nexus Consulting Group → monday.com")
    print(f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    print(f"\n  Result: {passed}/{total} checks passed", end="")
    print(" ✓" if failed == 0 else f"  ({failed} failed)")

    print_section("COUNT CHECKS")
    for check in count_checks:
        icon   = "✓" if check["pass"] else "✗"
        status = "PASS" if check["pass"] else "FAIL"
        print(f"  [{status}] {icon} {check['check']}: "
              f"expected {check['expected']}, got {check['actual']}")

    print_section("DATA INTEGRITY CHECKS")
    for check in id_checks + field_checks:
        render_check(check)

    print_section("STATUS NORMALIZATION — ENGAGEMENT")
    render_status_normalization_check(eng_status_check)

    print_section("STATUS NORMALIZATION — DELIVERABLES")
    render_status_normalization_check(del_status_check, label_width=32)

    print("\n" + "=" * 60)
    if failed == 0:
        print("  ✓ ALL CHECKS PASSED — Migration looks good")
    else:
        print(f"  ✗ {failed} CHECK(S) FAILED — Review issues above")
    print("=" * 60)

    report = {
        "generated_at": datetime.now().isoformat(),
        "summary":      {"passed": passed, "failed": failed, "total": total},
        "count_checks":               count_checks,
        "id_checks":                  id_checks,
        "field_checks":               field_checks,
        "engagement_status_check":    eng_status_check,
        "deliverable_status_check":   del_status_check,
    }
    with open(REPORT_PATH, "w") as f:
        json.dump(report, f, indent=2)
    print(f"\n  Full report written to: {REPORT_PATH}\n")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    if not API_TOKEN:
        print("Error: MONDAY_API_TOKEN not set.")
        sys.exit(1)

    if not os.path.exists(CONFIG_PATH):
        print(f"Error: {CONFIG_PATH} not found. Run migration.py first.")
        sys.exit(1)

    print("=" * 60)
    print("  Nexus Consulting Group — Migration Validation")
    print("=" * 60)

    with open(CONFIG_PATH) as f:
        config = json.load(f)

    eng_board_id  = config["engagements_board_id"]
    del_board_id  = config["deliverables_board_id"]
    eng_cols      = config["engagements_columns"]
    del_cols      = config["deliverables_columns"]
    eng_status_map = config["engagement_status_map"]
    del_status_map = config["deliverable_status_map"]

    print("\nLoading source CSV...")
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        source_rows = list(csv.DictReader(f))
    source_eng_ids = list(dict.fromkeys(r["engagement_id"] for r in source_rows))
    print(f"  Source: {len(source_rows)} deliverables, {len(source_eng_ids)} engagements")

    print("\nFetching monday.com board data...")
    monday_engs = fetch_board_items(eng_board_id)
    monday_dels = fetch_board_items(del_board_id)
    print(f"  monday: {len(monday_dels)} deliverables, {len(monday_engs)} engagements")

    print("\nRunning validation checks...")
    count_checks = check_record_counts(source_rows, source_eng_ids, monday_engs, monday_dels)
    id_checks    = [
        check_engagement_ids(source_rows, monday_engs, eng_cols),
        check_deliverable_ids(source_rows, monday_dels, del_cols),
    ]
    field_checks = [
        check_orphaned_deliverables(monday_dels, del_cols),
        check_required_fields(monday_dels, del_cols),
    ]
    eng_status_check = check_engagement_status_normalization(
        source_rows, monday_engs, eng_cols, eng_status_map
    )
    del_status_check = check_deliverable_status_normalization(
        source_rows, monday_dels, del_cols, del_status_map
    )

    render_report(count_checks, id_checks, field_checks, eng_status_check, del_status_check)


if __name__ == "__main__":
    main()
